// Human-readable labels for audit-log action keys. Shared between the on-screen
// table and the CSV export so both always show the same friendly wording (and
// never a raw machine key or DB id).
export const ACTION_LABELS: Record<string, string> = {
  'staff.added': 'Staff added',
  'staff.role_changed': 'Role changed',
  'staff.email_changed': 'Email changed',
  'staff.activated': 'Staff activated',
  'staff.deactivated': 'Staff deactivated',
  'staff.invite_resent': 'Invite resent',
  'staff.password_reset_sent': 'Password reset sent',
  'role.created': 'Role created',
  'role.renamed': 'Role renamed',
  'role.deleted': 'Role deleted',
  'role.permissions_changed': 'Permissions changed',
  'discount.approved': 'Discount approved',
  'discount.rejected': 'Discount rejected',
  'discount.recurring_revoked': 'Recurring discount revoked',
  'invoice.sent': 'Invoice sent',
  'invoice.sent_bulk': 'Invoices sent (bulk)',
  'invoice.generated': 'Invoice generated',
  'invoice.generated_bulk': 'Invoices generated (bulk)',
  'invoice.regenerated': 'Invoice regenerated',
  'invoice.regenerated_bulk': 'Invoices regenerated (bulk)',
  'discount.requested': 'Discount requested',
  'student.added': 'Student added',
  'student.imported': 'Students imported',
  'student.updated': 'Student updated',
  'student.status_changed': 'Student status changed',
  'student.opt_in_toggled': 'Fee opt-in toggled',
  'student.opt_in_bulk_updated': 'Fee opt-ins updated (bulk)',
  'student.exemption_set': 'Exemption set',
  'student.exemption_removed': 'Exemption removed',
  'student.dva_created': 'Payment account created',
  'student.dva_bulk_created': 'Payment accounts created (bulk)',
  'student.reminder_sent': 'Manual reminder sent',
  'family.updated': 'Family info updated',
  'family.notes_updated': 'Family notes updated',
  'class.added': 'Class added',
  'class.updated': 'Class updated',
  'class.active_toggled': 'Class active status toggled',
  'section.added': 'Section added',
  'section.updated': 'Section updated',
  'section.deleted': 'Section deleted',
  'session.created': 'Session created',
  'session.activated': 'Session activated',
  'session.closed': 'Session closed',
  'term.created': 'Term created',
  'term.updated': 'Term updated',
  'term.closed_carried_forward': 'Term closed & carried forward',
  'term.activated': 'Term activated',
  'term.closed': 'Term closed',
  'term.reopened_draft': 'Term reopened as draft',
  'term.draft_deleted': 'Term draft deleted',
  'year_end.started': 'Year-end rollover started',
  'year_end.resumed': 'Year-end rollover resumed',
  'year_end.cancelled': 'Year-end rollover cancelled',
  'fee_item.added': 'Fee item added',
  'fee_item.updated': 'Fee item updated',
  'fee_item.deleted': 'Fee item deleted',
  'fee_item.bulk_deleted': 'Fee items deleted (bulk)',
  'fee_group.updated': 'Fee group updated',
  'school.updated': 'School profile updated',
  'school.logo_uploaded': 'School logo uploaded',
  'school.logo_removed': 'School logo removed',
  'payment_config.updated': 'Payment provider settings updated',
  'discount_config.updated': 'Discount policy updated',
  'reminder_config.updated': 'Reminder settings updated',
  'account.password_changed': 'Password changed',
  'report.audit_log_downloaded': 'Audit log downloaded',
}

export function actionLabel(action: string): string {
  return ACTION_LABELS[action] || action
}
