import { LegalLayout, LegalSection } from "@/components/LegalLayout";
import { buildPageMetadata } from "@/lib/seo";

export const metadata = buildPageMetadata({
  title: "Privacy Policy",
  description:
    "How FEES101 LTD collects, uses and protects data on the Fees101 platform, in line with Nigeria's Data Protection Act (NDPA).",
  path: "/privacy",
});

const SECTIONS = [
  { id: "who-we-are", label: "1. Who we are" },
  { id: "controller-and-processor-roles", label: "2. Controller and processor roles" },
  { id: "information-we-collect", label: "3. Information we collect" },
  { id: "how-we-use-information", label: "4. How we use information" },
  { id: "who-we-share-information-with", label: "5. Who we share information with" },
  { id: "childrens-data", label: "6. Children's data" },
  { id: "data-retention", label: "7. Data retention" },
  { id: "data-security", label: "8. Data security" },
  { id: "your-rights", label: "9. Your rights" },
  { id: "contact-us", label: "10. Contact us" },
];

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" updated="24 July 2026" sections={SECTIONS}>
      <p>
        This Privacy Policy explains how <strong>FEES101 LTD</strong> (&ldquo;Fees101&rdquo;,
        &ldquo;we&rdquo;, &ldquo;us&rdquo;) collects, uses, and protects information
        in connection with our revenue operations platform. It is written to comply
        with the Nigeria Data Protection Act, 2023 (NDPA) and the regulations of the
        Nigeria Data Protection Commission (NDPC).
      </p>

      <LegalSection id="who-we-are" heading="1. Who we are">
        <p>
          Fees101 is operated by FEES101 LTD, RC 9694725, a company registered in
          Nigeria with its registered office at Plot L182, Ellicot Citi Street,
          Kubwa Extension III, Bwari, FCT, Nigeria.
        </p>
        <p>
          Fees101 provides software that Nigerian schools use to manage tuition and
          fee structures, generate student invoices, collect payments, and send
          payment notifications to parents/guardians.
        </p>
      </LegalSection>

      <LegalSection id="controller-and-processor-roles" heading="2. Controller and processor roles">
        <p>
          Schools that use Fees101 (&ldquo;School Customers&rdquo;) act as{" "}
          <strong>data controllers</strong> for the student and parent/guardian data
          they enter into the platform — they decide what data to collect and why.
          Fees101 acts as a <strong>data processor</strong>, handling that data only
          on the School Customer&rsquo;s instructions and for the purpose of
          providing the service.
        </p>
        <p>
          If you are a parent, guardian, or student and have questions about your
          data, your school is the first point of contact, since they control what
          information is submitted to us.
        </p>
      </LegalSection>

      <LegalSection id="information-we-collect" heading="3. Information we collect">
        <p>We process the following categories of information:</p>
        <ul className="list-disc pl-5">
          <li>
            <strong>School account data</strong> — school name, administrator
            names, email addresses, and login credentials.
          </li>
          <li>
            <strong>Student and family data</strong>, entered by schools — student
            names, class/term enrolment, and parent/guardian names and phone
            numbers, used to generate invoices and send payment notifications.
          </li>
          <li>
            <strong>Payment data</strong> — fee amounts, invoice and payment
            status, and virtual bank account details generated by our licensed
            payment infrastructure partner for each student. We do not store bank
            card numbers or full account credentials.
          </li>
          <li>
            <strong>Messaging data</strong> — the content and delivery status of
            SMS/WhatsApp notifications sent to parents/guardians (e.g. invoice and
            payment reminders), and the phone number they were sent to.
          </li>
          <li>
            <strong>Technical data</strong> — basic log and session data needed to
            keep the platform secure and operating correctly.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="how-we-use-information" heading="4. How we use information">
        <ul className="list-disc pl-5">
          <li>To generate and deliver fee invoices to the correct student/family.</li>
          <li>To provision and reconcile payments against the correct student.</li>
          <li>
            To send transactional notifications by SMS/WhatsApp — for example,
            new invoice alerts, payment confirmations, and payment reminders.
          </li>
          <li>To provide collection reporting and dashboards to School Customers.</li>
          <li>To maintain the security, integrity, and availability of the platform.</li>
        </ul>
        <p>We do not sell personal information, and we do not use it for advertising.</p>
      </LegalSection>

      <LegalSection id="who-we-share-information-with" heading="5. Who we share information with">
        <p>Data is shared only with service providers we use to operate Fees101, under contract:</p>
        <ul className="list-disc pl-5">
          <li>
            <strong>Payment infrastructure providers</strong> (e.g. Monnify,
            Paystack), to generate dedicated virtual bank accounts and process
            payments.
          </li>
          <li>
            <strong>Messaging providers</strong> (e.g. Sendchamp), to deliver SMS and
            WhatsApp notifications to parents/guardians on our behalf.
          </li>
          <li>
            <strong>Cloud infrastructure and database providers</strong> (e.g.
            Supabase), to securely host application data.
          </li>
        </ul>
        <p>
          We do not share personal data with third parties for their own
          independent marketing purposes.
        </p>
      </LegalSection>

      <LegalSection id="childrens-data" heading="6. Children&rsquo;s data">
        <p>
          Because Fees101 is used to manage school fees, it necessarily processes
          limited data about students, some of whom are minors. This data
          (typically name and class/term enrolment) is provided directly by the
          school for the specific purpose of invoicing and is not used for any
          other purpose. We do not knowingly collect data directly from children.
        </p>
      </LegalSection>

      <LegalSection id="data-retention" heading="7. Data retention">
        <p>
          We retain data for as long as a School Customer maintains an active
          account, and for a reasonable period afterward to meet legal,
          accounting, and dispute-resolution obligations. School Customers may
          request deletion of their data, subject to any records we are legally
          required to keep.
        </p>
      </LegalSection>

      <LegalSection id="data-security" heading="8. Data security">
        <p>
          We apply industry-standard technical and organisational measures to
          protect data, including encrypted connections, encrypted storage of
          sensitive credentials, and access controls restricting who within
          Fees101 can view data.
        </p>
      </LegalSection>

      <LegalSection id="your-rights" heading="9. Your rights">
        <p>Under the NDPA, individuals have the right to:</p>
        <ul className="list-disc pl-5">
          <li>Request access to personal data held about them;</li>
          <li>Request correction of inaccurate data;</li>
          <li>Request deletion or restriction of processing, in certain circumstances;</li>
          <li>Object to certain processing; and</li>
          <li>Lodge a complaint with the Nigeria Data Protection Commission (NDPC).</li>
        </ul>
        <p>
          Requests relating to student or parent/guardian data should generally be
          directed to the relevant school first. Requests relating to school
          account data can be sent to us directly using the contact details below.
        </p>
      </LegalSection>

      <LegalSection id="contact-us" heading="10. Contact us">
        <p>
          For any privacy questions or requests, contact us at{" "}
          <a href="mailto:support@fees101.com" className="text-signal-text underline">
            support@fees101.com
          </a>{" "}
          or{" "}
          <a href="mailto:support@fees101.com" className="text-signal-text underline">
            support@fees101.com
          </a>
          , or by post at:
        </p>
        <address className="not-italic">
          FEES101 LTD
          <br />
          Plot L182, Ellicot Citi Street, Kubwa Extension III, Bwari, FCT, Nigeria
          <br />
          RC 9694725
        </address>
      </LegalSection>
    </LegalLayout>
  );
}
